"""Pydantic schemas for NAMS API."""
from .common import (
    PaginationParams,
    PaginatedResponse,
    MessageResponse,
    ErrorResponse,
    RegionBase,
    RegionCreate,
    RegionUpdate,
    RegionResponse,
    EventTypeBase,
    EventTypeCreate,
    EventTypeUpdate,
    EventTypeResponse,
    OverviewStats,
    YearStats,
    RegionStats,
)
from .pattern import (
    PatternBase,
    PatternCreate,
    PatternUpdate,
    PatternResponse,
    PatternReorder,
    PatternTestRequest,
    PatternTestResult,
    PatternAffectedFiles,
)
from .file import (
    NasFileBase,
    NasFileCreate,
    NasFileUpdate,
    NasFileOverride,
    NasFileMoveRequest,
    NasFileBulkUpdate,
    NasFileResponse,
    NasFileListResponse,
    FileFilter,
)
from .group import (
    AssetGroupBase,
    AssetGroupCreate,
    AssetGroupUpdate,
    AssetGroupResponse,
    AssetGroupListResponse,
    AssetGroupDetailResponse,
    GroupSetPrimaryRequest,
    GroupMergeRequest,
    GroupSplitRequest,
    GroupFilter,
)
from .exclusion import (
    ExclusionRuleBase,
    ExclusionRuleCreate,
    ExclusionRuleUpdate,
    ExclusionRuleResponse,
    ExclusionRuleListResponse,
    ExclusionRuleTestRequest,
    ExclusionRuleTestResult,
)

__all__ = [
    # Common
    "PaginationParams",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    "RegionBase",
    "RegionCreate",
    "RegionUpdate",
    "RegionResponse",
    "EventTypeBase",
    "EventTypeCreate",
    "EventTypeUpdate",
    "EventTypeResponse",
    "OverviewStats",
    "YearStats",
    "RegionStats",
    # Pattern
    "PatternBase",
    "PatternCreate",
    "PatternUpdate",
    "PatternResponse",
    "PatternReorder",
    "PatternTestRequest",
    "PatternTestResult",
    "PatternAffectedFiles",
    # File
    "NasFileBase",
    "NasFileCreate",
    "NasFileUpdate",
    "NasFileOverride",
    "NasFileMoveRequest",
    "NasFileBulkUpdate",
    "NasFileResponse",
    "NasFileListResponse",
    "FileFilter",
    # Group
    "AssetGroupBase",
    "AssetGroupCreate",
    "AssetGroupUpdate",
    "AssetGroupResponse",
    "AssetGroupListResponse",
    "AssetGroupDetailResponse",
    "GroupSetPrimaryRequest",
    "GroupMergeRequest",
    "GroupSplitRequest",
    "GroupFilter",
    # Exclusion
    "ExclusionRuleBase",
    "ExclusionRuleCreate",
    "ExclusionRuleUpdate",
    "ExclusionRuleResponse",
    "ExclusionRuleListResponse",
    "ExclusionRuleTestRequest",
    "ExclusionRuleTestResult",
]
